node { 
    def buildDetails = checkoutWithDetails(buildNumber:env.BUILD_NUMBER)

    stage('Build') {
        def nodeHome = tool 'Node 7'
        env.PATH="${env.PATH}:${nodeHome}/bin"
        sh 'rm -rf node_modules'
        sh 'npm install'

        sh 'ng build --aot --source-map --output-path dist/test'
        sh 'ng build --aot --source-map --prod --output-path dist/prod '
    }

    if(env.BRANCH_NAME == "master") {
        buildDockerImage(buildDetails)
    }
}
